name: Build and Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore Dependencies
      run: dotnet restore "MinimalAPI/MinimalAPI.csproj"

    - name: Build All Projects
      run: dotnet build "MinimalAPI/MinimalAPI.csproj" --configuration Release

    - name: Publish MinimalAPI
      run: dotnet publish "MinimalAPI/MinimalAPI.csproj" --configuration Release --output ./publish

    - name: Create ZIP File
      run: |
        zip -r MinimalAPI.zip ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MinimalAPI
        path: MinimalAPI.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: MinimalAPI
        path: ./MinimalAPI

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

    - name: Deploy Application to Azure App Service
      run: |
        az webapp deploy \
          --resource-group quetstroey-rg-production-northeurope-01 \
          --name quetstroey-webapp-production \
          --src-path ./MinimalAPI/MinimalAPI.zip \
          --type zip
