name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore examples-aspnet-minimalapi.sln

      - name: Build and publish the application
        run: dotnet publish MinimalAPI/MinimalAPI.csproj -c Release -o ./publish

      - name: Archive the published application
        run: zip -r minimalapi.zip ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: minimalapi
          path: minimalapi.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: minimalapi

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure App Service
        run: |
          az webapp deploy \
            --name quetstroey-webapp-staging \
            --resource-group quetstroey-rg-staging-northeurope-01 \
            --src-path minimalapi.zip \
            --type zip
